### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by elanuser** [hashicorp/vault-plugin-auth-alicloud#28]
Our project  set AliCloud  as vault auth method, and config as document described.
vault version: Vault v1.1.3 ('9bc820f700f83a7c4bcab54c5323735a581b34eb')
but still faced following error with small chance.

vault login -method=alicloud
Error authenticating: Error making API request.

URL: PUT https://ip:8200/v1/auth/alicloud/login
Code: 500. Errors:

* error making upstream request: error making request: Post https://sts.aliyuncs.com/?AccessKeyId=&Action=GetCallerIdentity&Format=JSON&RegionId=&SecurityToken=&Signature=&SignatureMethod=HMAC-SHA1&SignatureNonce=&SignatureType=&SignatureVersion=1.0&Timestamp=2019-10-09T09%!A(MISSING)55%!A(MISSING)11Z&Version=2015-04-01: net/http: TLS handshake timeout

**Comment by alearon** [comment]
I am trying to do the same thing, I don't get a timeout but I do get issues with the signature:

`"Recommend":"https://error-center.aliyun.com/status/search?Keyword=SignatureDoesNotMatch&source=PopGw","Message":"Specified signature is not matched with our calculation. server string to sign is:`

When I curl the login URL for aliyun directly it appears to break with this error only when adding "&Format=JSON" to the URL. It responds correctly without this added parameter.

Has anyone else had any luck with this?

**Comment by fairclothjm** [comment]
Due to inactivity, we will close this issue. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
