### ISSUE TITLE
cross-account validating support

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/vault-plugin-auth-alicloud#29]
Hi,

Does this plugin support cross-account validating ram roles?
like this:
https://www.vaultproject.io/api-docs/auth/aws/
![image](https://user-images.githubusercontent.com/15604715/73716332-ab4b8e00-4751-11ea-9280-c0430e62e178.png)

**Comment by yongzhang** [comment]
@kalafut Looks you're the last one to commit on this project, are you able to look at this? Thanks a lot.

**Comment by tyrannosaurus-becks** [comment]
Hi! 

No, the AliCloud plugin doesn't support that currently. Cool to know there's an interest though!
