### ISSUE TITLE
When using the latest version of Alibaba Cloud sdk in client, an error occurs

### ISSUE THREAD

**Issue by ethan256** [hashicorp/vault-plugin-auth-alicloud#40]
When using the latest version of Alibaba Cloud sdk in client, the following error occurs：
```golang
expected host of "sts.aliyuncs.com" but received "sts.us-west-1.aliyuncs.com"
```

Because latest verstion of Alibaba Cloud sdk of sts service add regionId

**Comment by fairclothjm** [comment]
fixed in #43
