### ISSUE TITLE
is it able to use auth plugin to create a role and grant the policy to get an arn before writing "vault write alibaba/role/role-based role_arn=xxx " without using terraform api

### ISSUE THREAD

**Issue by Danny5487401** [hashicorp/vault-plugin-auth-alicloud#78]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/64348131/233521775-fe659242-1abb-4ccb-8153-b01782d7bca6.png">

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/64348131/233521976-f702d89c-fcdc-4a2f-b39d-acb449b125f3.png">

**Comment by fairclothjm** [comment]
@Danny5487401 Hello

Roles are associated with a role ARN that has been pre-created in AliCloud. AliCloud's console displays each role's ARN. A role in Vault has a 1:1 relationship with a role in AliCloud, and must bear the same name.

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) .

**Comment by Danny5487401** [comment]
@fairclothjm it is ok for me to use terraform to deal with
